### ISSUE TITLE
Video download error

### ISSUE THREAD

**Issue by edrkr96** [abwilf/Social-IQ-2.0-Challenge#1]
Hi, there!
I just tried to run the code python siq2/download_all.py but suffered from the following error:
ERROR: unable to download video data: HTTP Error 403: Forbidden
Could you help me fix the error? Thank you.

**Comment by edrkr96** [comment]
@abwilf 
Updating youtube dl package worked. Thank you!!

@msra-jqxu
In my case, 
`pip install --upgrade yt-dlp`
 worked.

**Comment by abwilf** [comment]
Glad to hear it! Closing the issue for now.
